### ISSUE TITLE
Handle string payload

### ISSUE THREAD

**Issue by tyx** [rezzza/jadd#14]
```
Warning: array_filter() expects parameter 1 to be array, string given in /var/vendor/rezzza/jadd/src/Domain/ApiResponse.php line 65
```

**Comment by polict** [comment]
I cloudn't find the correct line where array_filter() is being used, can you write again where exactly is the bug? :)

**Comment by shouze** [comment]
@polict yup it's actually in [ApiResponse:: cleanJson()](https://github.com/rezzza/jadd/blob/05fceabdc57d1ff70f5904a07e67587531f1aa7d/src/Domain/ApiResponse.php#L55-L66). It's when the result of `json_decode` call is not an array.

For example:

``` php
echo json_decode('"some valid json string"', true); // will return a string
```

So `array_filter()` can't be applied on it. We miss unit tests and a fix for this use case.

**Comment by shouze** [comment]
@polict we already have some unit tests written [here](https://github.com/rezzza/jadd/blob/388c894bac4e1a53b22d0f7a256afd98dfc2e121/tests/Units/Domain/ApiResponse.php). Unit tests are written with [atoum](http://atoum-en.readthedocs.io/en/latest/).

**Comment by polict** [comment]
What about `(array)json_encode([...])`? It'd always return an array, though I'd check the returned value if it's empty or not (for example `empty(array(json_decode('{"hello"}', true)))` returns true)... Let me know if it'd work for you so I can write the changes to the files :)

**Comment by shouze** [comment]
@polict In fact I think you just have to:
1. store the result of json_decode into as temporary variable.
2. check the returned type of this variable and return it directly if it's a string.
3. otherwise, return the array_filter like it's already done today.

And of course need the given unit test for json string responses.

**Comment by tyx** [comment]
Done in #21
